# Generated by Django 5.2.3 on 2025-06-27 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouchVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='touch_images/')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('HA', 'Haptic'), ('VI', 'Visual'), ('AU', 'Auditory'), ('OL', 'Olfactory'), ('GU', 'Gustatory')], max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
