# Generated by Django 5.2.3 on 2025-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchvariety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
